name: install dependencies
description: set up node & install dependencies
inputs:
  node-version:
    description: 'node version'
    required: false
    default: 20.12.0

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
        scope: '@jpyc'
    - name: Enable yarn
      shell: bash
      run: |
        corepack enable
        corepack prepare yarn@4.7.0 --activate
    - name: Install dependencies
      shell: bash
      run: yarn --frozen-lockfile
